In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


#creating numpy array

In [ ]:
#creating a 0d array
arr1=np.array(10)
print("0 dimensional array: ",arr1)

#creating a 1d array
arr2=np.array([1,2,3,4])
print("1 dimensional array: ",arr2)

#creating 2d array
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2d array: ",arr3)

#creating 3d array
arr4=np.array([ [ [1,2,3],[4,4,5] ], [ [6,78,9],[8,4,3] ] ])
print("3d array: ",arr4)


#check dimensions of an array
print("\n dimensions of an array arra 4: ", arr4.ndim)

print("\n dimensions of an array arra 3: ",arr3.ndim)

print("\n dimensions of an array arra 2: ", arr2.ndim)

print("\n dimensions of an array arra 1: ", arr1.ndim)

0 dimensional array:  10
1 dimensional array:  [1 2 3 4]
2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
3d array:  [[[ 1  2  3]
  [ 4  4  5]]

 [[ 6 78  9]
  [ 8  4  3]]]

 dimensions of an array arra 4:  3

 dimensions of an array arra 3:  2

 dimensions of an array arra 2:  1

 dimensions of an array arra 1:  0


In [ ]:
arr5=np.array([1,2,3,4],ndmin=5)
print(arr5)
print(arr5.ndim )

[[[[[1 2 3 4]]]]]
5


In [ ]:
arr6=np.array([1,2,3,4,5], ndmin=3)
print(arr6)
print(arr6.ndim)

[[[1 2 3 4 5]]]
3


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3])

4


In [ ]:
print(arr[1])

2


In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.ndim)
print(arr1)
print(arr1[1,0])

2
[[1 2 3 4]
 [5 6 7 8]]
5


In [ ]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr2.ndim,"dimentions of array")
print(arr2)
print(arr2[1,0,0:2])

3 dimentions of array
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
[7 8]


#array slicing

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[::2])
print(arr[::-2])
print(arr[2::-1])

[2 3 4 5]
[1 3 5]
[6 4 2]
[3 2 1]


#creating  array with zeroes and ones

In [ ]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr1=np.zeros((4,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr2=np.ones((3,5))*5
print(arr2)


arr4=np.ones((3,5))+5
print(arr4)

arr3=np.ones((2,5))
print(arr3)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#.eye function is used for identity matrix

arr11=np.eye(5,5)
print(arr11)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr11=np.eye(5,5)*0 +5
print(arr11)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
arr=np.full((3,5), 5, dtype='float')
print(arr)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
arr=np.full((3,5), 5, dtype='float')-3
print(arr)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


#create a matrix with random integer numbers

In [ ]:
arr=np.random.randint(1,100,20)
print(arr)

[ 4 74 77 83 27 71 29 82 54 63 75 36 76 57  2 90 63 88 95 36]


#create a numpy array of n number of elements seperated by eual distance

In [ ]:
ls=np.linspace(0,100,27)
print(ls)

[  0.           3.84615385   7.69230769  11.53846154  15.38461538
  19.23076923  23.07692308  26.92307692  30.76923077  34.61538462
  38.46153846  42.30769231  46.15384615  50.          53.84615385
  57.69230769  61.53846154  65.38461538  69.23076923  73.07692308
  76.92307692  80.76923077  84.61538462  88.46153846  92.30769231
  96.15384615 100.        ]


In [ ]:
ls1=np.linspace(0,50,40)
print(ls1)

[ 0.          1.28205128  2.56410256  3.84615385  5.12820513  6.41025641
  7.69230769  8.97435897 10.25641026 11.53846154 12.82051282 14.1025641
 15.38461538 16.66666667 17.94871795 19.23076923 20.51282051 21.79487179
 23.07692308 24.35897436 25.64102564 26.92307692 28.20512821 29.48717949
 30.76923077 32.05128205 33.33333333 34.61538462 35.8974359  37.17948718
 38.46153846 39.74358974 41.02564103 42.30769231 43.58974359 44.87179487
 46.15384615 47.43589744 48.71794872 50.        ]


In [ ]:
matrix=np.random.rand(3,5)
print(matrix)

[[0.01747863 0.47443072 0.11676942 0.26350946 0.2727747 ]
 [0.02839954 0.7786415  0.53747183 0.45107172 0.53044303]
 [0.54288557 0.84255785 0.1526193  0.52589735 0.07717888]]


In [ ]:
matrix.shape

(3, 5)

In [ ]:
x=matrix.reshape(5,3)
print(x)

[[0.01747863 0.47443072 0.11676942]
 [0.26350946 0.2727747  0.02839954]
 [0.7786415  0.53747183 0.45107172]
 [0.53044303 0.54288557 0.84255785]
 [0.1526193  0.52589735 0.07717888]]


In [ ]:
y=np.array([1,2,3,4,5,8,6,7,8,9,2,7])
y=y.reshape(2,3,2)
print(y)

[[[1 2]
  [3 4]
  [5 8]]

 [[6 7]
  [8 9]
  [2 7]]]


#create a numpy array with specific data type

In [ ]:
x=np.array([1,2,3,4,5], dtype='int')
print(x)
y=np.array(x, dtype='float')
print(y)
print(y.dtype)
print(y.shape)
print(y.ndim)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
float64
(5,)
1


#create a numpy array that have zero, one, two, three, four dimensions respectively

In [ ]:
x0=np.array(3)
x1=np.array([1,2,3,4])
x2=np.array([[1,2,3],[4,5,6]])
x3=np.array([ [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]])
x4=np.array([[ [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]], [ [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]]])

print(f'x0 dimension: {x0.ndim}')
print(f'x1 dimension: {x1.ndim}')
print(f'x2 dimension: {x2.ndim}')
print(f'x3 dimension: {x3.ndim}')
print(f'x4 dimensions : {x4.ndim}')
print(x4)


x0 dimension: 0
x1 dimension: 1
x2 dimension: 2
x3 dimension: 3
x4 dimensions : 4
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


In [ ]:
x=np.array([1,2,3,4,5,6,7,8,4,9,10,11,12], ndmin=4)
print(x)
print(x.ndim)


[[[[ 1  2  3  4  5  6  7  8  4  9 10 11 12]]]]
4


In [ ]:
x4=np.array([[ [[1,2,3],[4,5,6]] , [[1,2,3],[8,5,6]]], [ [[1,2,3],[4,9,6]] , [[1,22,3],[4,5,6]]]])

print(x4[0,1,1,0])
print(x4[1,1,0,1])

8
22


In [ ]:
# prompt: if i want to print 9 in x4 how

x4=np.array([[ [[1,2,3],[4,5,6]] , [[1,2,3],[4,5,6]]], [ [[1,2,3],[4,9,6]] , [[1,2,3],[4,5,6]]]])

print(x4[1,0,1,1])


9


In [ ]:
x=np.zeros((2,5), dtype='int')
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
y=np.eye(3,3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
z=np.full((3,5) ,5)
print(z)

z1=np.ones((3,5), dtype='int')*5
print(z1)

z2=np.zeros((3,5), dtype='int')+5
print(z2)

z3=np.eye(3,5)*0+5
print(z3)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
x=np.random.randint(0,100,25)
print(x)

[85 76  5 46 92 53 11 40 32 87 53 10 17 71 63 11 93 86 17  7 13 57 34 20
 45]


In [ ]:
y=np.full((3,5),1)
print(y)

y1=np.ones((3,5), dtype='int')
print(y1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
x=np.random.randint(0,100,(2,3))
print(x)

y=x.reshape((3,2))
print(y)

[[44 35 31]
 [57  2  8]]
[[44 35]
 [31 57]
 [ 2  8]]


##create a random array, with the range 0 to 1000 , with a size of 50

In [ ]:
#create a random array, with the range 0 to 1000 , with a size of 50

x=np.random.randint(0,1000,50)
print(x)

[171 251 266 489 955  99 450 713 328 589 263 191   8 859 607 984 791 481
 862 160 950 813 850 597 201 359 139 788 806 207 264 892  25 513 592 909
 757 488 474 853 468 601 788 850 470 890 982 548 479 756]


In [ ]:
#print fst 10 elements of the array

print(x[:10])

[171 251 266 489 955  99 450 713 328 589]


In [ ]:
#print last 10 elements

print(x[40:])

[468 601 788 850 470 890 982 548 479 756]


In [ ]:
#print the elements fro  the indexes 10 to 25
print(x[10:26])

[263 191   8 859 607 984 791 481 862 160 950 813 850 597 201 359]


In [ ]:
#print the elements in negative index
print(x[::-1])

[756 479 548 982 890 470 850 788 601 468 853 474 488 757 909 592 513  25
 892 264 207 806 788 139 359 201 597 850 813 950 160 862 481 791 984 607
 859   8 191 263 589 328 713 450  99 955 489 266 251 171]


In [ ]:
#print the last 10 elements
print(x[50:39:-1])

[756 479 548 982 890 470 850 788 601 468]


In [ ]:
#print the last 10 elements
print(x[-10:])

[468 601 788 850 470 890 982 548 479 756]


#Given a numpy array that has values =[1,2,3,4,5] and perform operations on it

In [ ]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [ ]:
#insert the element 6 at the end of the array
x=np.append(x,6)
print(x)

[1 2 3 4 5 6]


In [ ]:
#insert the element 10 at the begining of the array
x=np.insert(x,0,10)
print(x)

[10  1  2  3  4  5  6]


In [ ]:
#insert the element 30, before 4
x=np.insert(x,4,30)
print(x)

[10  1  2  3 30  4  5  6]


In [ ]:
#update the element 5 as 50
x[5]=50
print(x)

[10  1  2  3 30 50  5  6]


In [ ]:

x=np.delete(x,-1)
print(x)

[10  1  2  3 30 50  5]


In [ ]:


y=[1,2,3,4,5,6]
z=np.array(x)
old=2
new=20

arr_replace=np.where(z==old,new,z)
print(arr_replace)

[10  1 20  3 30 50  5]


In [ ]:
print(x)

[10  1  2  3 30 50  5]


In [ ]:
#delete the updated 50 element

x=np.delete(x,5)
print(x)

[10  1  2  3 30  5]


In [ ]:
#sort in decending order

x=np.sort(x)[::-1]
print(x)

[30 10  5  3  2  1]


In [ ]:
def check_element(arr,x):
  for i in arr:
    if i==x:
      return True
  return False

arr=np.array([4,23,86,5,3,9,2,7,22,1])
x=3

result=check_element(arr,x)

if result:
  print("element found")
else:
  print("element not found")

element found


In [ ]:
def check_element(arr,x):
  return np.any(arr==x)
  #np.any will returm boolean value, True if found, False if not found

arr=np.array([4,23,86,5,3,9,2,7,22,1])
x=3

result=check_element(arr,x)

if result:
  print("element found")
else:
  print("element not found")

element found


In [ ]:
i=np.array([70,23,76,96,26,19,56,20])
asc_sorting=np.sort(i)
desc_sorting=np.sort(i)[::-1]
print(asc_sorting)
print(desc_sorting)

[19 20 23 26 56 70 76 96]
[96 76 70 56 26 23 20 19]


In [ ]:
#check for element 3 in the given array

arr=np.array([4,23,86,5,9,2,7,22,1])
x=3
found=False
for i in range(0,len(arr)):
  if arr[i]==x:
    found=True
    break


if found:
  print("element found")
else:
  print("element not found")

element not found


In [ ]:

import numpy as np

arr=np.array([4,23,86,5,9,2,7,3,22,1])
x=3
element_found = False # Flag to track if the element is found
for i in range(0,len(arr)):
  if arr[i]==x:
    element_found = True # Set the flag to True if element is found
    break

if element_found:
  print("element found")
else:
  print("element not found")


element found


In [ ]:
import numpy as np

def check_element(arr, x):
  element_found = False
  for i in range(len(arr)):
    if arr[i] == x:
      element_found = True
      break
  return element_found

# Example usage
arr = np.array([4, 23, 86, 5, 9, 2, 7, 3, 22, 1])
x = 3
if check_element(arr, x):
    print("element found")
else:
    print("element not found")

x = 10
if check_element(arr,x):
  print("element found")
else:
  print("element not found")


element found
element not found
